### ISSUE TITLE
Not working properly inside Bootstrap Modal

### ISSUE THREAD

**Issue by jitendravyas** [alxlit/bootstrap-chosen#54]
![chosen](https://cloud.githubusercontent.com/assets/77309/7560491/536e7324-f7e1-11e4-9d3f-fb044d287ea4.png)

**Comment by alxlit** [comment]
Could you put together an example (maybe on jsfiddle)?

**Comment by gregopet** [comment]
I've had the same issue so I created a jsfiddle example: https://jsfiddle.net/jh4r372u/1/

I suspect the problem is due to the modal being hidden initally and will likely require a Javascript solution.

**Comment by gregopet** [comment]
A great answer about this on Stack Overflow: http://stackoverflow.com/questions/19089337/chosen-with-bootstrap-3-not-working-properly

**Comment by alxlit** [comment]
Thanks @gregopet!

**Comment by pihug12** [comment]
I'm not sure why this issue is closed whereas no fix or doc was committed. I struggled with this problem for quite some time.

The hack to apply:
* https://github.com/harvesthq/chosen/issues/2822#issuecomment-309215145
* https://stackoverflow.com/questions/19089337/chosen-with-bootstrap-3-not-working-properly/25943654#25943654
